// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtwJLaLf8oyRSvOQMPRtM-4NeQaxEIFsU',
    appId: '1:548821198340:web:f7b3f5ddff5a8185063751',
    messagingSenderId: '548821198340',
    projectId: 'onu-smart-app-5e37f',
    authDomain: 'onu-smart-app-5e37f.firebaseapp.com',
    storageBucket: 'onu-smart-app-5e37f.appspot.com',
    measurementId: 'G-KK0J435R51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMhHDUh-EuxKUamoabDTtxvrU6P-BJgMo',
    appId: '1:548821198340:android:e181c196185ebf80063751',
    messagingSenderId: '548821198340',
    projectId: 'onu-smart-app-5e37f',
    storageBucket: 'onu-smart-app-5e37f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIvslsYdhezJ4Ku_8fCU44qMaGFvk3uHY',
    appId: '1:548821198340:ios:6d6d9d72ba38e586063751',
    messagingSenderId: '548821198340',
    projectId: 'onu-smart-app-5e37f',
    storageBucket: 'onu-smart-app-5e37f.appspot.com',
    iosBundleId: 'com.example.onuSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIvslsYdhezJ4Ku_8fCU44qMaGFvk3uHY',
    appId: '1:548821198340:ios:ec225341b4b0c3e6063751',
    messagingSenderId: '548821198340',
    projectId: 'onu-smart-app-5e37f',
    storageBucket: 'onu-smart-app-5e37f.appspot.com',
    iosBundleId: 'com.example.onuSmart.RunnerTests',
  );
}
